### PR TITLE
feat: Add contributing guidelines

### LINKED ISSUE #9: [FEATURE] Create CONTRIBUTING.md to update README.md
### Is your feature request related to a problem? Please describe.

Need to enhance [README.md](https://github.com/devstrons/contest-bot/blob/main/README.md) in a way that, `Guidelines to follow` should be at `CONTRIBUTING.md`.

Also, change the stickers to medium size, that will be flexible & good looking.
Definitely, contributors shall add more stickers according to their own customization.

### Describe the solution you'd like

Need at creating `CONTRIBUTING.md`, to solve the requirements of the repository & make more flexible to contribute in!

### Describe alternatives you've considered

N.A.

### Additional context

Make sure, the "banner" shouldn't get damage from anywhere! :slightly_smiling_face: 
We're really concern about that stuff!

Thanks!

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Add contributing guidelines.
  - I think the `Guidelines to follow` part fits more in the `README.md` file
  than in the contribution guidelines. Let me know what do you think, though. 🙂
  - Closes #9.

### CODE REVIEW

**Comment by Panquesito7** [comment]
@amino19?

**Comment by amino19** [comment]
@Panquesito7: Need to add [contribution section](https://github.com/devstrons/contest-bot#-guidelines-to-follow) with the [testing section](https://github.com/devstrons/contest-bot#-testing) inside `Contributing.md` as well!

Make sure it looks amazing! :raised_hands:

**Comment by Panquesito7** [comment]
> @Panquesito7: Need to add [contribution section](https://github.com/devstrons/contest-bot#-guidelines-to-follow) with the [testing section](https://github.com/devstrons/contest-bot#-testing) inside `Contributing.md` as well!
> 
> Make sure it looks amazing! 🙌

Hmm, don't you think that's more for the readme? Because these are the contributing guidelines, "how to contribute to the project". Should we ask other maintainers their opinions?

**Comment by amino19** [comment]
> > @Panquesito7: Need to add [contribution section](https://github.com/devstrons/contest-bot#-guidelines-to-follow) with the [testing section](https://github.com/devstrons/contest-bot#-testing) inside `Contributing.md` as well!
> > Make sure it looks amazing! raised_hands
> 
> Hmm, don't you think that's more for the readme? Because these are the contributing guidelines, "how to contribute to the project". Should we ask other maintainers their opinions?

I'm asking to put everything inside `Contributing.md`, _rather than README.md._
Do you mind read the comment again?

**Comment by Panquesito7** [comment]
> > > @Panquesito7: Need to add [contribution section](https://github.com/devstrons/contest-bot#-guidelines-to-follow) with the [testing section](https://github.com/devstrons/contest-bot#-testing) inside `Contributing.md` as well!
> > > Make sure it looks amazing! raised_hands
> > 
> > 
> > Hmm, don't you think that's more for the readme? Because these are the contributing guidelines, "how to contribute to the project". Should we ask other maintainers their opinions?
> 
> I'm asking to put everything inside `Contributing.md`, _rather than README.md._ Do you mind read the comment again?

OK, so, I'll add those two parts in the contributing file. Nothing else should be added?

**Comment by amino19** [comment]
> > > > @Panquesito7: Need to add [contribution section](https://github.com/devstrons/contest-bot#-guidelines-to-follow) with the [testing section](https://github.com/devstrons/contest-bot#-testing) inside `Contributing.md` as well!
> > > > Make sure it looks amazing! raised_hands
> > > 
> > > 
> > > Hmm, don't you think that's more for the readme? Because these are the contributing guidelines, "how to contribute to the project". Should we ask other maintainers their opinions?
> > 
> > 
> > I'm asking to put everything inside `Contributing.md`, _rather than README.md._ Do you mind read the comment again?
> 
> OK, so, I'll add those two parts in the contributing file. Nothing else should be added?

Yes, nothing shall need to add. :slightly_smiling_face:

**Comment by aminoxix** [comment]
I'm working on the same, thanks for your contribution so far! 🙂

**Pull request merged**
