### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by amino19**
**Description**
License changed from MIT to GNU GPL 3.0

### CODE REVIEW

**Comment by Panquesito7** [comment]
When changing licenses, you must ask all those who contributed to this repository if they agree, you can't just change it like that.
Maybe we should make an issue regarding that, and for now, revert this pull request. What do you think? 🙂

**Comment by amino19** [comment]
Thanks, @Panquesito7 for raising it!

@JOS-RE (maintainer), @forscht (collaborator), & @ghulamyazdani (maintainer): Folks, do you like to write your feedback here?

**Comment by ghulamyazdani** [comment]
@Panquesito7, Is there any problem regarding the license? We already discussed this.

**Comment by JOS-RE** [comment]
@amino19 : We already discussed this earlier, thanks for taking this up.

**Comment by Panquesito7** [comment]
> @Panquesito7, Is there any problem regarding the license? We already discussed this.

As far as I know, if the license is going to be changed, all contributors have to agree to change it. But if you folks already discussed it, it is all good. Sorry for the inconvenience. 😓

**Comment by forscht** [comment]
@amino19  Go ahead!

**Pull request merged**
